#!/usr/bin/env ruby

puts "Enter the name of the kata:"
kata_name = readline.chomp.strip.gsub(" ","_").downcase

`mkdir #{kata_name}`

current_time = Time.now
date_string = current_time.strftime("%Y_%m_%d")
full_path = kata_name + "/" + date_string

`cp -R template #{full_path}`

puts "Launching Visual Studio . . ."
`"C:/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE/devenv.exe" ./#{full_path}/solution.sln`